import { useState } from 'react';
import { Protect } from '@clerk/clerk-react';
import * as pdfjsLib from 'pdfjs-dist';
// Import worker as a URL for Vite
import workerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
import './Study.css';

// Configure PDF.js worker
pdfjsLib.GlobalWorkerOptions.workerSrc = workerUrl;

/**
 * Study Coach MVP Component
 * 
 * A single-page study coach that helps learners practice recall:
 * 1. Upload PDF → Extract text
 * 2. Enter study goal
 * 3. Generate and display relevant passages
 * 4. Show comprehension questions
 * 5. Evaluate answers and provide feedback
 */
function Study() {
  // Stage management: "upload" | "goal" | "reading" | "quiz" | "feedback"
  const [stage, setStage] = useState("upload");
  
  // Document text extracted from PDF
  const [text, setText] = useState("");
  
  // User's study goal
  const [goal, setGoal] = useState("");
  
  // Passages generated by GPT
  const [passages, setPassages] = useState([]);
  
  // Questions generated by GPT
  const [questions, setQuestions] = useState([]);
  
  // User's answers to questions
  const [answers, setAnswers] = useState(["", "", ""]);
  
  // Feedback from GPT evaluation
  const [feedback, setFeedback] = useState([]);
  
  // Loading states
  const [isExtracting, setIsExtracting] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isEvaluating, setIsEvaluating] = useState(false);
  
  // Error state
  const [error, setError] = useState("");

  /**
   * Extract text from uploaded PDF file
   * Uses pdfjs-dist to parse PDF in the browser
   */
  const extractTextFromPDF = async (file) => {
    setIsExtracting(true);
    setError("");
    
    try {
      const arrayBuffer = await file.arrayBuffer();
      const pdf = await pdfjsLib.getDocument({ data: arrayBuffer }).promise;
      
      let fullText = "";
      
      // Extract text from all pages
      for (let pageNum = 1; pageNum <= pdf.numPages; pageNum++) {
        const page = await pdf.getPage(pageNum);
        const textContent = await page.getTextContent();
        const pageText = textContent.items
          .map(item => item.str)
          .join(" ");
        fullText += pageText + "\n";
      }
      
      if (!fullText.trim()) {
        throw new Error("No text could be extracted from the PDF. Please ensure the PDF contains readable text.");
      }
      
      setText(fullText);
      setStage("goal");
    } catch (err) {
      setError(`Failed to extract text: ${err.message}`);
      console.error("PDF extraction error:", err);
    } finally {
      setIsExtracting(false);
    }
  };

  /**
   * Handle file upload
   */
  const handleFileUpload = (event) => {
    const file = event.target.files[0];
    if (!file) return;
    
    if (file.type !== "application/pdf") {
      setError("Please upload a PDF file.");
      return;
    }
    
    extractTextFromPDF(file);
  };

  /**
   * Generate passages and questions from the study text and goal
   * Calls OpenAI API to get relevant passages and comprehension questions
   */
  const generateQuestions = async () => {
    if (!goal.trim()) {
      setError("Please enter a study goal.");
      return;
    }
    
    setIsGenerating(true);
    setError("");
    
    try {
      const apiKey = import.meta.env.VITE_OPENAI_API_KEY;
      if (!apiKey) {
        throw new Error("OpenAI API key not found. Please add VITE_OPENAI_API_KEY to your .env file.");
      }
      
      const response = await fetch("https://api.openai.com/v1/chat/completions", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${apiKey}`,
        },
        body: JSON.stringify({
          model: "gpt-5-nano",
          messages: [
            {
              role: "system",
              content: "You are a study coach that helps learners develop deep understanding through recall practice. Always respond with valid JSON only, no additional text."
            },
            {
              role: "user",
              content: `Given this study text:\n${text.substring(0, 8000)}\n\nand the user's goal: ${goal}\n\nSelect three short relevant passages (max 250 words each) and generate three short-answer questions to test comprehension. Return structured JSON in this exact format: {"passages": ["passage 1 text", "passage 2 text", "passage 3 text"], "questions": ["question 1", "question 2", "question 3"]}`
            }
          ],
          response_format: { type: "json_object" }
        })
      });
      
      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(errorData.error?.message || `API error: ${response.statusText}`);
      }
      
      const data = await response.json();
      const content = JSON.parse(data.choices[0].message.content);
      
      setPassages(content.passages || []);
      setQuestions(content.questions || []);
      setStage("reading");
    } catch (err) {
      setError(`Failed to generate questions: ${err.message}`);
      console.error("Question generation error:", err);
    } finally {
      setIsGenerating(false);
    }
  };

  /**
   * Evaluate user's answers and provide feedback
   * Calls OpenAI API to assess understanding
   */
  const evaluateAnswers = async () => {
    if (answers.some(answer => !answer.trim())) {
      setError("Please answer all questions before submitting.");
      return;
    }
    
    setIsEvaluating(true);
    setError("");
    
    try {
      const apiKey = import.meta.env.VITE_OPENAI_API_KEY;
      if (!apiKey) {
        throw new Error("OpenAI API key not found.");
      }
      
      


      const response = await fetch("https://api.openai.com/v1/chat/completions", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${apiKey}`,
        },
        body: JSON.stringify({
          model: "gpt-5-nano",
          messages: [
            {
              role: "system",
              content: "You are a study coach evaluating a student's understanding. Always respond with valid JSON only, no additional text."
            },
            {
              role: "user",
              content: `Here is the study text:\n${text.substring(0, 8000)}\n\nGoal: ${goal}\n\nQuestions:\n${questions.map((q, i) => `${i + 1}. ${q}`).join("\n")}\n\nUser Answers:\n${answers.map((a, i) => `${i + 1}. ${a}`).join("\n")}\n\nEvaluate each answer on a scale of 0-1 and give a brief 1-2 sentence feedback for each. Return a JSON object with a "feedback" key containing an array. Use this exact format: {"feedback": [{"question": "question text", "score": 0.8, "comment": "feedback text"}, ...]}`
            }
          ],
          response_format: { type: "json_object" }
        })
      });
      
      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(errorData.error?.message || `API error: ${response.statusText}`);
      }
      
      const data = await response.json();
      console.log("🔵 Raw API Response:", data);  // ADD THIS
      console.log("🔵 Message Content (raw string):", data.choices[0].message.content);  // ADD THIS

      const content = JSON.parse(data.choices[0].message.content);
      console.log("🟢 Parsed Content:", content);  // ADD THIS
      console.log("🟢 Is Array?", Array.isArray(content));  // ADD THIS
      console.log("🟢 Content Type:", typeof content);  // ADD THIS
      
      // Handle both array and object with feedback key
      const feedbackArray = Array.isArray(content) 
  ? content 
  : (content.response || content.feedback ||content.results || []);
      console.log("🟡 Extracted Feedback Array:", feedbackArray);  // ADD THIS
      console.log("🟡 Feedback Array Length:", feedbackArray.length);
      
      setFeedback(feedbackArray);
      console.log("🟣 State updated, feedback set to:", feedbackArray);  // ADD THIS
      setStage("feedback");
      console.log("🟣 Stage set to 'feedback'");
      
    } catch (err) {
      setError(`Failed to evaluate answers: ${err.message}`);
      console.error("Evaluation error:", err);
    } finally {
      setIsEvaluating(false);
    }
  };

  /**
   * Handle answer input change
   */
  const handleAnswerChange = (index, value) => {
    const newAnswers = [...answers];
    newAnswers[index] = value;
    setAnswers(newAnswers);
  };

  /**
   * Reset the study session
   */
  const resetStudy = () => {
    setStage("upload");
    setText("");
    setGoal("");
    setPassages([]);
    setQuestions([]);
    setAnswers(["", "", ""]);
    setFeedback([]);
    setError("");
  };

  // Helper to get progress circle className
  const getProgressCircleClass = (s, i) => {
    const stages = ["upload", "goal", "reading", "quiz", "feedback"];
    const currentIndex = stages.indexOf(stage);
    
    let baseClass = "study-progress-circle";
    if (stage === s) {
      return `${baseClass} active`;
    } else if (currentIndex > i) {
      return `${baseClass} completed`;
    } else {
      return `${baseClass} pending`;
    }
  };

  // Helper to get progress line className
  const getProgressLineClass = (i) => {
    const stages = ["upload", "goal", "reading", "quiz", "feedback"];
    const currentIndex = stages.indexOf(stage);
    
    let baseClass = "study-progress-line";
    if (currentIndex > i) {
      return `${baseClass} completed`;
    } else {
      return `${baseClass} pending`;
    }
  };

  // Helper to get score badge className
  const getScoreBadgeClass = (score) => {
    const numScore = typeof score === 'number' ? score : parseFloat(score);
    let baseClass = "study-score-badge";
    if (numScore >= 0.8) {
      return `${baseClass} excellent`;
    } else if (numScore >= 0.6) {
      return `${baseClass} good`;
    } else {
      return `${baseClass} needs-improvement`;
    }
  };

  return (
    <div className="study-container">
    <div className="study-wrapper">
    <Protect
        fallback={
          <div className="study-card" style={{ textAlign: 'center', padding: '3rem' }}>
            <h2>Sign In Required</h2>
            <p>Please sign in to access the Study Coach feature.</p>
          </div>
        }
      >
       


      
        {/* Header */}
        <div className="study-header">
          <h1 className="study-title">Study Coach</h1>
          <p className="study-subtitle">Practice active recall to deepen your understanding</p>
        </div>

        {/* Progress Indicator */}
        <div className="study-progress-container">
          {["upload", "goal", "reading", "quiz", "feedback"].map((s, i) => (
            <div key={s} className="study-progress-step">
              <div className={getProgressCircleClass(s, i)}>
                {i + 1}
              </div>
              {i < 4 && <div className={getProgressLineClass(i)} />}
            </div>
          ))}
        </div>

        {/* Error Display */}
        {error && (
          <div className="study-error-box">
            {error}
          </div>
        )}

        {/* Stage 1: Upload */}
        {stage === "upload" && (
          <div className="study-card">
            <h2 className="study-heading">Step 1: Upload Your Study Material</h2>
            <p className="study-text">Upload a PDF document to begin your study session.</p>
            
            <div className="study-upload-area">
              <input
                type="file"
                accept="application/pdf"
                onChange={handleFileUpload}
                className="study-hidden"
                id="pdf-upload"
                disabled={isExtracting}
              />
              <label htmlFor="pdf-upload">
                <div className="study-upload-icon">📄</div>
                <div className="study-upload-text">
                  {isExtracting ? "Extracting text..." : "Click to upload PDF"}
                </div>
                {isExtracting && (
                  <div className="study-spinner"></div>
                )}
              </label>
            </div>
            
            {text && (
              <div className="study-success-box">
                ✓ Text extracted successfully ({text.length} characters)
              </div>
            )}
          </div>
        )}

        {/* Stage 2: Goal */}
        {stage === "goal" && (
          <div className="study-card">
            <h2 className="study-heading">Step 2: Set Your Study Goal</h2>
            <p className="study-text">
              What would you like to focus on? This helps generate relevant passages and questions.
            </p>
            
            <textarea
              value={goal}
              onChange={(e) => setGoal(e.target.value)}
              placeholder="e.g., Understand the key concepts of machine learning, Focus on the historical context of World War II..."
              className="study-textarea"
              rows="4"
            />
            
            <button
              onClick={generateQuestions}
              disabled={isGenerating || !goal.trim()}
              className="study-button"
            >
              {isGenerating ? (
                <span className="study-button-loading">
                  <span>⏳</span>
                  Generating questions...
                </span>
              ) : (
                "Generate Study Materials"
              )}
            </button>
          </div>
        )}

        {/* Stage 3: Reading */}
        {stage === "reading" && (
          <div className="study-card">
            <h2 className="study-heading">Step 3: Read and Review</h2>
            <p className="study-text">
              Read through these passages carefully. When you're ready, click the button below to test your understanding.
            </p>
            
            <div className="study-mb-3">
              {passages.map((passage, index) => (
                <div key={index} className="study-passage-box">
                  <h3 className="study-passage-title">
                    Passage {index + 1}
                  </h3>
                  <p className="study-passage-text">{passage}</p>
                </div>
              ))}
            </div>
            
            <button
              onClick={() => setStage("quiz")}
              className="study-button"
            >
              I'm Ready
            </button>
          </div>
        )}

        {/* Stage 4: Quiz */}
        {stage === "quiz" && (
          <div className="study-card">
            <h2 className="study-heading">Step 4: Answer the Questions</h2>
            <p className="study-text">
              Answer these questions based on what you read. Write short, thoughtful responses.
            </p>
            
            <div className="study-mb-3">
              {questions.map((question, index) => (
                <div key={index} className="study-passage-box">
                  <h3 className="study-passage-title">
                    Question {index + 1}
                  </h3>
                  <p className="study-question-text">{question}</p>
                  <textarea
                    value={answers[index]}
                    onChange={(e) => handleAnswerChange(index, e.target.value)}
                    placeholder="Type your answer here..."
                    className="study-textarea"
                    rows="4"
                  />
                </div>
              ))}
            </div>
            
            <button
              onClick={evaluateAnswers}
              disabled={isEvaluating || answers.some(a => !a.trim())}
              className="study-button"
            >
              {isEvaluating ? (
                <span className="study-button-loading">
                  <span>⏳</span>
                  Evaluating your answers...
                </span>
              ) : (
                "Submit Answers"
              )}
            </button>
          </div>
        )}

        {/* Stage 5: Feedback */}
        {stage === "feedback" && (
          <div className="study-card">
            <h2 className="study-heading">Step 5: Your Feedback</h2>
            <p className="study-text">
              Here's how you did and what you can improve:
            </p>
            
            <div className="study-mb-3">
              {feedback.map((item, index) => (
                <div key={index} className="study-passage-box">
                  <div className="study-feedback-header">
                    <h3 className="study-passage-title">
                      Question {index + 1}
                    </h3>
                    <span className={getScoreBadgeClass(item.score)}>
                      Score: {typeof item.score === 'number' ? item.score.toFixed(1) : item.score}
                    </span>
                  </div>
                  <p className="study-question-text study-mb-1">{item.question || questions[index]}</p>
                  <p className="study-answer-text">
                    Your answer: {answers[index]}
                  </p>
                  <p className="study-feedback-text">
                    {item.comment || item.feedback || "No feedback provided."}
                  </p>
                </div>
              ))}
            </div>
            
            <button
              onClick={resetStudy}
              className="study-button"
            >
              Start New Study Session
            </button>
          </div>
        )}
      
      
      </Protect>
    </div>
    </div>
  );
}

export default Study;
